openapi: 3.0.1
info:
  title: RestRserve OpenAPI
  version: '1.0'
servers:
- url: /
paths:
  /lodscan:
    get:
      get:
        description: Get scan information.
        responses:
          '200':
            description: API response
            content:
              application/json:
                schema:
                  type: string
                  example: 5
          '400':
            description: API Error
            content:
              application/json:
                schema:
                  type: string
                  example: Server error
  /lodscansamples:
    get:
      get:
        description: Get scan by sample information.
        responses:
          '200':
            description: API response
            content:
              application/json:
                schema:
                  type: string
                  example: 5
          '400':
            description: API Error
            content:
              application/json:
                schema:
                  type: string
                  example: Server error
